apiVersion: v1
kind: ConfigMap
metadata:
  name: fu-berlin-config
  namespace: studentvc-production
data:
  TENANT_NAME: "FU Berlin"
  SERVER_URL: "https://fu-berlin.studentvc.org"
  ENVIRONMENT: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: fu-berlin-secrets
  namespace: studentvc-production
type: Opaque
data:
  # Base64 encoded secrets - replace with actual production values
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0BkYi9zdHVkZW50dmM=
  SECRET_KEY: cHJvZHVjdGlvbi1zZWNyZXQta2V5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fu-berlin-production
  namespace: studentvc-production
  labels:
    app: fu-berlin
    environment: production
    university: fu-berlin
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: fu-berlin
      environment: production
  template:
    metadata:
      labels:
        app: fu-berlin
        environment: production
        university: fu-berlin
    spec:
      containers:
      - name: studentvc
        image: ghcr.io/pherbke/studentvc:${IMAGE_TAG}
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: fu-berlin-config
        - secretRef:
            name: fu-berlin-secrets
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: instance-storage
          mountPath: /src/instance
        - name: logs
          mountPath: /var/log/studentvc
      volumes:
      - name: instance-storage
        persistentVolumeClaim:
          claimName: fu-berlin-production-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: fu-berlin-logs-pvc
      imagePullSecrets:
      - name: ghcr-secret
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - fu-berlin
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: fu-berlin-production-service
  namespace: studentvc-production
spec:
  selector:
    app: fu-berlin
    environment: production
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fu-berlin-production-ingress
  namespace: studentvc-production
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - fu-berlin.studentvc.org
    secretName: fu-berlin-production-tls
  rules:
  - host: fu-berlin.studentvc.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fu-berlin-production-service
            port:
              number: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fu-berlin-production-pvc
  namespace: studentvc-production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fu-berlin-logs-pvc
  namespace: studentvc-production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fu-berlin-production-hpa
  namespace: studentvc-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fu-berlin-production
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80